//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda_TB
    {
        public int Agenda_ID { get; set; }
        public int Agenda_Cita_ID { get; set; }
        public Nullable<short> Agenda_Horario_ID { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Citas_TB Citas_TB { get; set; }
        public virtual Horarios_TB Horarios_TB { get; set; }
    }
}
