//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citas_TB()
        {
            this.Agenda_TB = new HashSet<Agenda_TB>();
        }
    
        public int Cita_ID { get; set; }
        public Nullable<int> Cita_Cliente_ID { get; set; }
        public Nullable<short> Cita_MP_ID { get; set; }
        public Nullable<short> Cita_Consultorio_ID { get; set; }
        public Nullable<int> Cita_ME_ID { get; set; }
        public Nullable<int> Cita_Fact_ID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Finalizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda_TB> Agenda_TB { get; set; }
        public virtual Consultorio_TB Consultorio_TB { get; set; }
        public virtual Facturas_TB Facturas_TB { get; set; }
        public virtual Medicos_Especialidades_TB Medicos_Especialidades_TB { get; set; }
        public virtual Metodos_Pago_TB Metodos_Pago_TB { get; set; }
        public virtual Clientes_TB Clientes_TB { get; set; }
    }
}
