//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes_Padecimientos_TB
    {
        public int CP_ID { get; set; }
        public int CP_Cliente_ID { get; set; }
        public int CP_Padecimiento_ID { get; set; }
        public string CP_Comentarios { get; set; }
    }
}
