//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horarios_TB()
        {
            this.Agenda_TB = new HashSet<Agenda_TB>();
        }
    
        public short Horario_ID { get; set; }
        public string Dia { get; set; }
        public Nullable<System.DateTime> Hora_Inicio { get; set; }
        public Nullable<System.DateTime> Hora_Fin { get; set; }
        public string Disponible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda_TB> Agenda_TB { get; set; }
    }
}
