//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicos_TB
    {
        public int Numero_Carne { get; set; }
        public int Doctor_Empleado_ID { get; set; }
    
        public virtual Empleados_TB Empleados_TB { get; set; }
    }
}
