//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedimientos_TB
    {
        public short Procedimiento_ID { get; set; }
        public short Procedimiento_Especialidad_ID { get; set; }
        public string Descripcion { get; set; }
        public decimal Costo { get; set; }
    
        public virtual Especialidades_TB Especialidades_TB { get; set; }
    }
}
