//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjetas_TB
    {
        public int Numero_Tarjeta { get; set; }
        public int Tarjeta_Cliente_ID { get; set; }
        public System.DateTime Fecha_Vencimiento { get; set; }
    
        public virtual Clientes_TB Clientes_TB { get; set; }
    }
}
