//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios_TB()
        {
            this.Empleados_TB = new HashSet<Empleados_TB>();
            this.Clientes_TB = new HashSet<Clientes_TB>();
        }
    
        public string Usuario_ID { get; set; }
        public string Password { get; set; }
        public short Tipo_Perfil { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados_TB> Empleados_TB { get; set; }
        public virtual Tipos_Perfiles_TB Tipos_Perfiles_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes_TB> Clientes_TB { get; set; }
    }
}
